
USE [master]
GO

/****** Object:  Database [DatabaseV1]    Script Date: 12/23/2016 2:13:50 PM ******/
CREATE DATABASE [DatabaseV1]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DatabaseV1', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLEXPRESS\MSSQL\DATA\DatabaseV1.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DatabaseV1_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLEXPRESS\MSSQL\DATA\DatabaseV1_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [DatabaseV1] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DatabaseV1].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DatabaseV1] SET ANSI_NULL_DEFAULT OFF
GO

ALTER DATABASE [DatabaseV1] SET ANSI_NULLS OFF
GO

ALTER DATABASE [DatabaseV1] SET ANSI_PADDING OFF
GO

ALTER DATABASE [DatabaseV1] SET ANSI_WARNINGS OFF
GO

ALTER DATABASE [DatabaseV1] SET ARITHABORT OFF
GO

ALTER DATABASE [DatabaseV1] SET AUTO_CLOSE ON
GO

ALTER DATABASE [DatabaseV1] SET AUTO_SHRINK OFF
GO

ALTER DATABASE [DatabaseV1] SET AUTO_UPDATE_STATISTICS ON
GO

ALTER DATABASE [DatabaseV1] SET CURSOR_CLOSE_ON_COMMIT OFF
GO

ALTER DATABASE [DatabaseV1] SET CURSOR_DEFAULT  GLOBAL
GO

ALTER DATABASE [DatabaseV1] SET CONCAT_NULL_YIELDS_NULL OFF
GO

ALTER DATABASE [DatabaseV1] SET NUMERIC_ROUNDABORT OFF
GO

ALTER DATABASE [DatabaseV1] SET QUOTED_IDENTIFIER OFF
GO

ALTER DATABASE [DatabaseV1] SET RECURSIVE_TRIGGERS OFF
GO

ALTER DATABASE [DatabaseV1] SET  ENABLE_BROKER
GO

ALTER DATABASE [DatabaseV1] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO

ALTER DATABASE [DatabaseV1] SET DATE_CORRELATION_OPTIMIZATION OFF
GO

ALTER DATABASE [DatabaseV1] SET TRUSTWORTHY OFF
GO

ALTER DATABASE [DatabaseV1] SET ALLOW_SNAPSHOT_ISOLATION OFF
GO

ALTER DATABASE [DatabaseV1] SET PARAMETERIZATION SIMPLE
GO

ALTER DATABASE [DatabaseV1] SET READ_COMMITTED_SNAPSHOT ON
GO

ALTER DATABASE [DatabaseV1] SET HONOR_BROKER_PRIORITY OFF
GO

ALTER DATABASE [DatabaseV1] SET RECOVERY SIMPLE
GO

ALTER DATABASE [DatabaseV1] SET  MULTI_USER
GO

ALTER DATABASE [DatabaseV1] SET PAGE_VERIFY CHECKSUM
GO

ALTER DATABASE [DatabaseV1] SET DB_CHAINING OFF
GO

ALTER DATABASE [DatabaseV1] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF )
GO

ALTER DATABASE [DatabaseV1] SET TARGET_RECOVERY_TIME = 60 SECONDS
GO

ALTER DATABASE [DatabaseV1] SET DELAYED_DURABILITY = DISABLED
GO

ALTER DATABASE [DatabaseV1] SET QUERY_STORE = OFF
GO

USE [DatabaseV1]
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

USE [DatabaseV1]
GO

/****** Object:  Table [dbo].[__MigrationHistory]    Script Date: 12/23/2016 2:13:50 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  Table [dbo].[AspNetRoles]    Script Date: 12/23/2016 2:13:50 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  Table [dbo].[AspNetUserClaims]    Script Date: 12/23/2016 2:13:50 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  Table [dbo].[AspNetUserLogins]    Script Date: 12/23/2016 2:13:50 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  Table [dbo].[AspNetUserRoles]    Script Date: 12/23/2016 2:13:50 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  Table [dbo].[AspNetUsers]    Script Date: 12/23/2016 2:13:50 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

SET ANSI_PADDING ON
GO

SET ANSI_PADDING ON
GO

SET ANSI_PADDING ON
GO

SET ANSI_PADDING ON
GO

SET ANSI_PADDING ON
GO

USE [master]
GO

ALTER DATABASE [DatabaseV1] SET  READ_WRITE
GO
